### ISSUE TITLE
too slow

### ISSUE THREAD

**Issue by ucassee** [replikation/What_the_Phage#123]
Hi,

I use the following command to run wtp with an input fasta file (~60M):
`nextflow run replikation/What_the_Phage --fasta wtp/all_combined.fasta --databases nextflow-autodownload-databases --cachedir singularity_images --output wtpresult   --cores 20  -profile local,singularity  -r v1.0.0`

I find the ` hmmsearch` step only running with one thread. I wonder whether some configure file I should modify to speed up this process.

It finished with errors and I attached the report.
[execution_report.zip](https://github.com/replikation/What_the_Phage/files/5722945/execution_report.zip)

When I use the same command on a cluster (PBS system), it showed the following error:
```
Command error:
  INFO:    Convert SIF file to sandbox...
  ERROR  : Failed to create user namespace: user namespace disabled
```
How can I debug?

Thanks

**Comment by replikation** [comment]
hi, can you specifiy which process you mean ?

based on the report file i can only see that the "identify" workflow was executed not the annotation workflow.

in this case: `identify_fasta_MSF` but not a `phage_annotation_MSF`

either way you can modify ram/cpu usage locally via this file: https://github.com/replikation/What_the_Phage/blob/master/configs/local.config

hhmscan currently uses all the cores locally. can you add the `--max_cores 20` flag an check if it works then?

**Comment by replikation** [comment]
the issue was a missing hardware configuration for virsorter 2. we will push a hotfix release today to fix that

**Comment by mult1fractal** [comment]
Hey,

we fixed the config files where virsorter 2 was missing.
* use `-r v1.0.1` and re-execute your command

**Comment by ucassee** [comment]
Hi @replikation, 
       I am not sure which process it was.
       But the command is like this `hmmsearch -T 30 --tblout iter-0/all.pdg.faa.splitdir/all.pdg.faa.ss.1.split.Viruses.splithmmtbl --cpu 1 --noali -o /dev/null /db/hmm/viral/combined.hmm /tmp/vs2-K6zvoLzjXZlu/all.pdg.faa.ss.1.split` 
       I will try new version.

**Comment by ucassee** [comment]
Hi,
    There is still an error when I use a non-root acount. How can I debug this?

Error executing process > 'identify_fasta_MSF:fasta_validation_wf:input_suffix_check (1)'

```
Caused by:
  Process `identify_fasta_MSF:fasta_validation_wf:input_suffix_check (1)` terminated with an error exit status (1)

Command executed:

  case "test.fasta" in
      *.gz) 
          zcat test.fasta > test.fa
          ;;
      *.fna)
          cp test.fasta test.fa
          ;;
      *.fasta)
          cp test.fasta test.fa
          ;;
      *.fa)
          ;;
      *)
          echo "file format not supported...what the phage...(.fa .fasta .fna .gz is supported)"
          exit 1
  esac
  
  # tr whitespace at the end of lines
  sed 's/[[:blank:]]*$//' -i test.fa
  # remove ' and "
  tr -d "'"  < test.fa | tr -d '"' | tr -d "[]" > tmp.file && mv tmp.file test.fa
  # replace ( ) | . , / and whitespace with _
  sed 's#[()|.,/ ]#_#g' -i test.fa
  # remove empty lines
  sed '/^$/d' -i test.fa

Command exit status:
  1

Command output:
  (empty)

Command error:
  INFO:    Convert SIF file to sandbox...
  ERROR  : Failed to create user namespace: user namespace disabled
```

Thanks

**Comment by replikation** [comment]
i think that has to be configured from the e.g. cluster-admin side of things I think (https://github.com/hpcng/singularity/issues/5240)

**Comment by ucassee** [comment]
Hi,
    I met a new error. How can I  debug? Thanks.

```
Error executing process > 'identify_fasta_MSF:fasta_validation_wf:input_suffix_check (1)'

Caused by:
  Process `identify_fasta_MSF:fasta_validation_wf:input_suffix_check (1)` terminated with an error exit status (255)

Command executed:

  case "all_pos_phage.fa" in
      *.gz) 
          zcat all_pos_phage.fa > all_pos_phage.fa
          ;;
      *.fna)
          cp all_pos_phage.fa all_pos_phage.fa
          ;;
      *.fasta)
          cp all_pos_phage.fa all_pos_phage.fa
          ;;
      *.fa)
          ;;
      *)
          echo "file format not supported...what the phage...(.fa .fasta .fna .gz is supported)"
          exit 1
  esac
  
  # tr whitespace at the end of lines
  sed 's/[[:blank:]]*$//' -i all_pos_phage.fa
  # remove ' and "
  tr -d "'"  < all_pos_phage.fa | tr -d '"' | tr -d "[]" > tmp.file && mv tmp.file all_pos_phage.fa
  # replace ( ) | . , / and whitespace with _
  sed 's#[()|.,/ ]#_#g' -i all_pos_phage.fa
  # remove empty lines
  sed '/^$/d' -i all_pos_phage.fa

Command exit status:
  255

Command output:
  (empty)

Command error:
  INFO:    Convert SIF file to sandbox...
  FATAL:   while extracting /data/database/wtp/singularity_images/nanozoo-basics-1.0--962b907.img: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found

Work dir:
   /data/Project/1.Mariana/4.virus/wtptempt/06/a6e46c15f82e227d71fd2c533ae0e1

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
```

**Comment by hoelzer** [comment]
This still looks like a problem with Singularity on your system:

```
Command error:
  INFO:    Convert SIF file to sandbox...
  FATAL:   while extracting /data/database/wtp/singularity_images/nanozoo-basics-1.0--962b907.img: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found
```

What is your version? 

```
singularity --version
```

Was singularity installed by a system administrator and configured appropriately?  

You can also try if singularity works outside of the Nextflow framework of WtP:

```
singularity run /data/database/wtp/singularity_images/nanozoo-basics-1.0--962b907.img wget --version
```

**Comment by ucassee** [comment]
Hi @hoelzer,
My singularity version is 3.6.3. I use conda to install it with my own account.

when run `singularity run /data/database/wtp/singularity_images/nanozoo-basics-1.0--962b907.img wget --version` with the same error:

```
INFO:    Convert SIF file to sandbox...
FATAL:   while extracting /data/database/wtp/singularity_images/nanozoo-basics-1.0--962b907.img: root filesystem extraction failed: could not extract squashfs data, unsquashfs not found 
```

**Comment by hoelzer** [comment]
@ucassee okay the version should be fine. 

But I experienced issues in the past when installing Singularity via conda on an HPC system where I'm not root. Are you running the pipeline on a (administrated) cluster machine? HPC, work station, ... or similar? 

If so, I think you should ask your system admin to install Singularity properly with root access. E.g., I did it using the following manual/notes on my local machine: 

https://hackmd.io/@GqOnlbqgSdKAMwgCUU_ljQ/rklBUfXRD

**Comment by ucassee** [comment]
Hi @hoelzer 
I will try to contact the system admin of our cluster.
But when I run the wtp using our work station. It is still going error with some virus prediction tools. I uploaded one report. Can I debug this or it is okay to ignore them?

Thanks
[execution_report.zip](https://github.com/replikation/What_the_Phage/files/5784709/execution_report.zip)

**Comment by hoelzer** [comment]
@ucassee it looks like three virus prediction tools failed:

* seeker
* virnet
* pprmeta

Although that is not nice, it can happen based on your input that some tools will not work. But WtP will run through anyway with the other tools. When you run the test profile on your work station, do these three tools work in general? Than it's fine and no need for debugging

**Comment by replikation** [comment]
we can take a look at this, but as martin metnioned we "autoskip" tools if they fail for various reasons so you get actual results and are not annoyed with tons of bugs :) 

We would need the "temporary dirs" to check out whats going on.

the following dirs would be of interest (located in the work dir):
```
40/f579e2*
8f/67a0ad*
4c/752a29*
```
inside are hidden files like `.command.log`.  And an `ls -lah` per dir would also be great so you dont need to send us the whole fasta input - but we need to know which "files were present" during the error.

thanks

**Comment by ucassee** [comment]
Hi @replikation @hoelzer 

Thanks for your reply. If you need any other files, please let me know.
[virnet.zip](https://github.com/replikation/What_the_Phage/files/5790072/virnet.zip)
[pprmeta.zip](https://github.com/replikation/What_the_Phage/files/5790074/pprmeta.zip)
[seeker_wf.zip](https://github.com/replikation/What_the_Phage/files/5790075/seeker_wf.zip)

**Comment by ucassee** [comment]
Hi,
I run the test profile, but there is still one error. I attached the report.
Thanks
[phigaro.zip](https://github.com/replikation/What_the_Phage/files/5806430/phigaro.zip)
[execution_report.zip](https://github.com/replikation/What_the_Phage/files/5806433/execution_report.zip)

**Comment by mult1fractal** [comment]
I will look into it tomorrow

**Comment by mult1fractal** [comment]
Hey,
unfortunately I was not able to reproduce your error with:
```shell
nextflow run phage.nf --cores 16 -profile local,smalltest,singularity
```

I checked the phigaro.zip file  `.command.err` :
`WARNING: underlay of /etc/localtime required more than 50 (95) bind mounts`

It seems this is linked to CentOS and using singularity...
I will try to find a solution for this

**Comment by ucassee** [comment]
Hi @mult1fractal,
Thanks for your effort, when you solve it please let me know. If I could find some clues, I will also report here.

**Comment by ucassee** [comment]
Hi @mult1fractal 
WTP seems to run all identifiers parallelly.  I used a local server to run it and saw a heavy load at the beginning. Sometimes I use a bigger assembly file (>500MB), my server crashed and restarted.
Do these relate to the error I met before?
Thanks

**Comment by replikation** [comment]
@ucassee Could you please provide the command used? The amount of parallel runs is basically controlled via the cores flag in relation to the max_cores on a local run.

**Comment by ucassee** [comment]
Hi @replikation 
The following is the command:
```
nextflow run /data2017/.nextflow/assets/replikation/What_the_Phage --fasta ${i} \
             --cachedir /data2017/database/wtp/singularity_images \
             --databases /data2017/database/wtp/nextflow-autodownload-databases \
             --output wtpresult/${n} \
             --workdir wtptempt  \
             --cores 6 \
             -profile local,singularity \
             --filter 10000 --identify 
```

**Comment by ucassee** [comment]
Hi all,

The .command.sh  of the phigaro is the following:

```
#!/bin/bash -ue
phigaro -f Dive121-T2_filtered.fa -o output -t 6 --wtp --config /root/.phigaro/config.yml
cat output/phigaro.txt > output/phigaro_${PWD##*/}.txt 
echo "" >> output/phigaro_${PWD##*/}.txt
```

But there is no config file at  /root/.phigaro/config.yml. So is this also related to the error I reported before.

**Comment by ucassee** [comment]
the error of phigaro can be debugged by using` phigaro-setup` in the singularity environment.

But the following step only called 1 thread, I wonder how to use more threads.
` hmmsearch -T 30 --tblout iter-0/all.pdg.faa.splitdir/all.pdg.faa.0.split.Viruses.splithmmtbl --cpu 1 --noali -o /dev/null /db/hmm/viral/combined.hmm /tmp/vs2-DjvgJ5JdjQnV/all.pdg.faa.0.split  `

**Comment by ucassee** [comment]
The tensorflow version in pprmeta image is 2.3, but the old CPU that doesn't support avx will have `Illegal instruction (core dumped)` problem.
Please see here https://github.com/tensorflow/tensorflow/issues/17411

I suggest you use tensorflow==1.5 to regenerate the image for compatibility with the older CPU.
Thanks

**Comment by mult1fractal** [comment]
Okay...
for virnet pprmeta and seeker:  I can try to build the images with ` tensorflow==1.5` but I'm not sure if the tools will work with this version of tensorflow

for Phigaro: I'm not able to reproduce this error with your command you posted above, nor with the command I used:
```shell
nextflow run replikation/What_the_Phage --cores 16 -profile local,smalltest,singularity --dv --ma --mp --pp --sm --vf --vn --vs --vs2 --sk --vb --cachedir singularity_images/ --identify -r v1.0.1
```
I will try  both commands with a larger Inputfile, maybe this causes the issue

**Comment by ucassee** [comment]
Hi @mult1fractal ,
For Phigaro error, I use `singularity multifractal-phigaro-0.5.2.img` and `phigaro-setup` to generate the config file `/root/.phigaro/config.yml`. 

I also used a new server that supports avx, so I can get the results from all wrapped tools now.

**Comment by ucassee** [comment]
Hi @mult1fractal @replikation, 

Virnet is designed for virus reads identification, not for assembly. Please see https://github.com/alyosama/virnet/issues/8
I think this is a cause of the virnet error, so I suggest you remove it from WTP. 
I see a new tool having good performance in virus identification. Also, attached here for you to consider. https://github.com/ablab/viralVerify

I am using wtp for my next project, you provide a powerful and convenient workflow.
Best

**Comment by mult1fractal** [comment]
Hey @ucassee 


before the input-fasta sequence gets to virnet, we [split the fasta file into 3000bp chunks](https://github.com/replikation/What_the_Phage/blob/master/bin/cut.py)  as suggested from the virnet-Dev. 


Okay nice, I will check it and put it on our list of tools to integrate.
